name: Build Expo App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build Android app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
        run: npx expo build:android --non-interactive

      - name: Build iOS app
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_ACCESS_TOKEN }}
        run: npx expo build:ios --non-interactive
